server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bin?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#  security:
#    user:
#      name: 123
#      password: 123
mybatis-plus:
  type-aliases-package: com.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: enable
      logic-delete-value: 0
      logic-not-delete-value: 1